namespace Enums
{
    public enum COMMUNICATION_METHODS
    {
        // it's going to be GRAAAAAAAAND:D
        
        //Client tell Server what to call:
        HANDLE_REQUEST_JOIN_LOBBY,
        HANDLE_PLAYER_READY,
        HANDLE_BEGIN_ROUND,
        HANDLE_TRADE_BANK,
        HANDLE_BUILD,
        HANDLE_TRADE_PORT,
        HANDLE_BUY_DEVELOPMENT,
        HANDLE_PLAY_DEVELOPMENT,
        HANDLE_END_TURN,
        HANDLE_CLIENT_DISCONNECT_SERVER_CALL,
        // Server tell Client what to call:
        HANDLE_CLIENT_JOINED,
        HANDLE_GAMESTART_INITIALIZE,
        HANDLE_DISTRIBUTE_RESOURCES,
        HANDLE_OBJECT_PLACEMENT,
        HANDLE_NEXT_PLAYER,
        HANDLE_VICTORY,
        HANDLE_PLAYER_TO_PLAYER_REQUEST,
        HANDLE_CLIENT_DISCONNECT,
        
        HANDLE_REJECTION,
        HANDLE_PLAYER_READY_NOTIFICATION,
        HANDLE_ACCEPT_BEGIN_ROUND,
        HANDLE_ACCEPT_TRADE_BANK,
        HANDLE_ACCEPT_TRADE_PORT,
        HANDLE_ACCEPT_BUILD,
        HANDLE_GET_RESOURCES,
        HANDLE_ACCEPT_BUY_DEVELOPMENT_CARD,
        HANDLE_ACCEPT_PLAY_DEVELOPMENT_CARD
    }
}